# Use a minimal Python image
FROM python:3.13-slim

# Install system packages
RUN apt-get update && \
    apt-get install -y build-essential curl git \
    pocl-opencl-icd \
    ocl-icd-opencl-dev

WORKDIR /app

COPY . .

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

CMD ["python", "src/main.py"]
